// This file is part of Moodle - http://moodle.org/.
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.

/**
 * Course index progress controller for theme Compecer.
 *
 * Consumes the dataset generated by {@link theme_compecer\output\courseindex_progress}
 * to render course, section and activity level progress indicators and keeps
 * them in sync with completion changes handled by core course editor components.
 *
 * @module     theme_compecer/courseindex_progress
 * @copyright  2024 IngeWeb
 * @license    http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */

import Str from 'core/str';

const STATUS_CLASSES = ['notstarted', 'inprogress', 'completed', 'failed'];
const stringCache = new Map();

/**
 * Initialise the course index progress enhancements.
 *
 * @param {string} drawerId DOM identifier of the course index drawer.
 */
export const init = (drawerId) => {
    const drawer = document.getElementById(drawerId);
    if (!drawer) {
        return;
    }

    let dataset = parseDataset(drawer.dataset.progress);
    if (!dataset.enabled) {
        // Even if completion is disabled we ensure the summary text is accurate.
        updateCourseHeader(drawer, dataset);
        return;
    }

    const observer = new MutationObserver(() => {
        refreshState(drawer, dataset).catch(() => null);
    });

    const contentRegion = drawer.querySelector('[data-region="courseindex-content"]');
    if (contentRegion) {
        observer.observe(contentRegion, {childList: true, subtree: true});
    }

    // Initial render after current microtask to ensure the drawer content has been loaded.
    window.requestAnimationFrame(() => {
        refreshState(drawer, dataset).catch(() => null);
    });
};

/**
 * Refresh the course, section and activity summaries.
 *
 * @param {HTMLElement} drawer The drawer root element.
 * @param {Object} dataset The mutable dataset shared with the template.
 */
const refreshState = async (drawer, dataset) => {
    const modules = [...drawer.querySelectorAll('[data-for="cm"]')];
    const sections = [...drawer.querySelectorAll('[data-for="section"]')];

    modules.forEach((cm) => {
        const cmid = parseInt(cm.dataset.id, 10);
        const status = determineActivityStatus(cm, dataset.activities[cmid]);
        if (!status) {
            return;
        }
        dataset.activities[cmid] = {
            status: status.status,
            label: dataset.strings[status.status],
        };
        applyActivityStatus(cm, dataset.activities[cmid]);
    });

    const courseCounts = initCounter();

    for (const section of sections) {
        const stats = summariseSection(section, dataset.activities);
        const sectionId = parseInt(section.dataset.id, 10);
        const existing = dataset.sections[sectionId] || {};
        const summary = await getString('sectionprogresssummary', {
            completed: stats.completed,
            total: stats.tracked,
        });
        const aria = await getString('sectionprogressaria', {
            completed: stats.completed,
            total: stats.tracked,
            percentage: stats.percentage,
        });

        dataset.sections[sectionId] = {
            ...existing,
            tracked: stats.tracked,
            completed: stats.completed,
            failed: stats.failed,
            inprogress: stats.inprogress,
            notstarted: stats.notstarted,
            percentage: stats.percentage,
            summary,
            aria,
        };
        applySectionProgress(section, dataset.sections[sectionId]);
        aggregateCounts(courseCounts, stats);
    }

    const coursePercentage = percentage(courseCounts.completed, courseCounts.tracked);
    const courseSummary = await getString('courseprogresssummary', {
        completed: courseCounts.completed,
        total: courseCounts.tracked,
        percentage: coursePercentage,
    });
    const courseAria = await getString('courseprogressaria', {
        percentage: coursePercentage,
    });

    dataset.course = {
        percentage: coursePercentage,
        completed: courseCounts.completed,
        failed: courseCounts.failed,
        inprogress: courseCounts.inprogress,
        notstarted: courseCounts.notstarted,
        total: courseCounts.tracked,
        summary: courseSummary,
        aria: courseAria,
        percentageformatted: `${coursePercentage}%`,
    };

    updateCourseHeader(drawer, dataset);
};

/**
 * Parse the dataset stored in the drawer element.
 *
 * @param {string} raw Raw JSON data.
 * @returns {Object}
 */
const parseDataset = (raw) => {
    if (!raw) {
        return {
            enabled: false,
            course: {},
            sections: {},
            activities: {},
            strings: {},
        };
    }
    try {
        return JSON.parse(raw);
    } catch (e) {
        return {
            enabled: false,
            course: {},
            sections: {},
            activities: {},
            strings: {},
        };
    }
};

/**
 * Determine the status for the provided course module element.
 *
 * @param {HTMLElement} cmElement
 * @param {Object} currentData
 * @returns {{status: string}|null}
 */
const determineActivityStatus = (cmElement, currentData = null) => {
    const completionNode = cmElement.querySelector('.completioninfo');
    if (!completionNode) {
        return null;
    }

    if (completionNode.classList.contains('completion_complete')) {
        return {status: 'completed'};
    }

    if (completionNode.classList.contains('completion_fail')) {
        return {status: 'failed'};
    }

    if (completionNode.classList.contains('completion_none')) {
        return null;
    }

    // The core exporter only differentiates between incomplete and complete.
    // Preserve the more granular status provided by PHP when available.
    if (currentData && currentData.status === 'inprogress') {
        return {status: 'inprogress'};
    }

    return {status: 'notstarted'};
};

/**
 * Apply status classes and accessible text to a course module row.
 *
 * @param {HTMLElement} cmElement
 * @param {Object} statusData
 */
const applyActivityStatus = (cmElement, statusData) => {
    const container = cmElement.querySelector('[data-region="cm-status"]');
    const textNode = cmElement.querySelector('[data-region="cm-status-text"]');
    if (!container || !textNode) {
        return;
    }

    STATUS_CLASSES.forEach((state) => container.classList.remove(`course-index-status--${state}`));
    container.classList.add(`course-index-status--${statusData.status}`);
    textNode.textContent = statusData.label || '';
};

/**
 * Compute completion summary for a section element.
 *
 * @param {HTMLElement} sectionElement
 * @param {Object} activities
 * @returns {Object}
 */
const summariseSection = (sectionElement, activities) => {
    const stats = initCounter();
    const modules = sectionElement.querySelectorAll('[data-for="cm"]');
    modules.forEach((cm) => {
        const cmid = parseInt(cm.dataset.id, 10);
        if (!activities[cmid]) {
            return;
        }
        stats.tracked += 1;
        stats[activities[cmid].status] += 1;
    });
    stats.percentage = percentage(stats.completed, stats.tracked);
    return stats;
};

/**
 * Apply visual section progress indicators.
 *
 * @param {HTMLElement} sectionElement
 * @param {Object} stats
 * @param {Object} dataset
 */
const applySectionProgress = (sectionElement, sectionData) => {
    const valueNode = sectionElement.querySelector('[data-region="section-progress-value"]');
    const barNode = sectionElement.querySelector('[data-region="section-progress-bar"]');
    const srNode = sectionElement.querySelector('[data-region="section-progress-text"]');
    if (!valueNode || !barNode || !srNode) {
        return;
    }

    const summary = sectionData.summary || '';
    const aria = sectionData.aria || '';

    const value = sectionData.tracked > 0 ? `${sectionData.completed}/${sectionData.tracked}` : '0/0';
    valueNode.textContent = value;
    barNode.style.setProperty('--section-progress', `${sectionData.percentage}%`);
    srNode.textContent = aria || summary;
};

/**
 * Update the course level header values.
 *
 * @param {HTMLElement} drawer
 * @param {Object} dataset
 */
const updateCourseHeader = (drawer, dataset) => {
    const valueNode = drawer.querySelector('[data-region="course-progress-value"]');
    const summaryNode = drawer.querySelector('[data-region="course-progress-summary"]');
    const bar = drawer.querySelector('.course-index-overview__fill');
    if (!valueNode || !summaryNode || !bar) {
        return;
    }

    if (!dataset.course) {
        return;
    }

    const percentageValue = dataset.course.total
        ? percentage(dataset.course.completed, dataset.course.total)
        : 0;

    valueNode.textContent = dataset.course.total ? `${percentageValue}%` : dataset.course.percentageformatted || `${percentageValue}%`;
    summaryNode.textContent = dataset.course.summary || summaryNode.textContent;
    bar.style.setProperty('--course-progress', `${percentageValue}%`);
    if (dataset.course.total) {
        bar.setAttribute('aria-valuenow', percentageValue);
    } else {
        bar.removeAttribute('aria-valuenow');
    }
    bar.setAttribute('aria-label', dataset.course.aria || '');
};

/**
 * Aggregate section counts into the course counter.
 *
 * @param {Object} courseCounts
 * @param {Object} sectionCounts
 */
const aggregateCounts = (courseCounts, sectionCounts) => {
    courseCounts.tracked += sectionCounts.tracked;
    courseCounts.completed += sectionCounts.completed;
    courseCounts.failed += sectionCounts.failed;
    courseCounts.inprogress += sectionCounts.inprogress;
    courseCounts.notstarted += sectionCounts.notstarted;
};

/**
 * Initialise a blank counter object.
 *
 * @returns {Object}
 */
const initCounter = () => ({
    tracked: 0,
    completed: 0,
    failed: 0,
    inprogress: 0,
    notstarted: 0,
});

/**
 * Safe percentage helper.
 *
 * @param {number} completed
 * @param {number} total
 * @returns {number}
 */
const percentage = (completed, total) => {
    if (!total) {
        return 0;
    }
    return Math.round((completed / total) * 100);
};

/**
 * Fetch and cache a language string.
 *
 * @param {string} key
 * @param {Object} params
 * @returns {Promise<string>}
 */
const getString = (key, params = {}) => {
    const cacheKey = JSON.stringify({key, params});
    if (!stringCache.has(cacheKey)) {
        stringCache.set(cacheKey, Str.get_string(key, 'theme_compecer', params));
    }
    return stringCache.get(cacheKey);
};

export default {init};
