<?php
// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.

/**
 * Format remuiformat renderer override for theme_inteb
 * Provides custom rendering to show ALL teachers (editing + non-editing)
 *
 * @package   theme_inteb
 * @copyright 2025 INTEB
 * @license   http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */

namespace theme_inteb\output;

defined('MOODLE_INTERNAL') || die();

require_once($CFG->dirroot . '/course/format/remuiformat/renderer.php');

/**
 * Renderer override for format_remuiformat
 *
 * This renderer intercepts the rendering of courses with remuiformat format
 * and modifies teacher data to show ALL teachers (editing + non-editing)
 * without modifying the format_remuiformat plugin.
 */
class format_remuiformat_renderer extends \format_remuiformat_renderer {

    /**
     * Renders the card one section page.
     *
     * OVERRIDE: Intercepts rendering to inject complete teacher data
     *
     * @param \format_remuiformat\output\format_remuiformat_card_one_section $activity Object of Activity renderable
     */
    public function render_card_one_section(
        \format_remuiformat\output\format_remuiformat_card_one_section $activity) {

        // Get template context from activity object
        $templatecontext = $activity->export_for_template($this);

        // MODIFICATION: Replace teacher data with complete version
        $templatecontext = $this->inject_all_teachers_data($templatecontext, $activity);

        // Render with modified context
        echo $this->render_from_template('format_remuiformat/card_one_section', $templatecontext);
    }

    /**
     * Renders the list one section page.
     *
     * OVERRIDE: Intercepts rendering to inject complete teacher data
     *
     * @param \format_remuiformat\output\format_remuiformat_list_one_section $activity Object of Activity renderable
     */
    public function render_list_one_section(
        \format_remuiformat\output\format_remuiformat_list_one_section $activity) {

        // Get template context from activity object
        $templatecontext = $activity->export_for_template($this);

        // MODIFICATION: Replace teacher data with complete version
        $templatecontext = $this->inject_all_teachers_data($templatecontext, $activity);

        // Render with modified context
        echo $this->render_from_template('format_remuiformat/list_one_section', $templatecontext);
    }

    /**
     * Injects complete teacher data (editing + non-editing) into template context
     *
     * @param \stdClass $templatecontext Template context generated by export_for_template()
     * @param object $activity Renderable object (card or list)
     * @return \stdClass Modified context with complete teacher data
     */
    private function inject_all_teachers_data($templatecontext, $activity) {
        // Verify that headerdata section with teachers exists
        if (!isset($templatecontext->headerdata) || !is_object($templatecontext->headerdata)) {
            return $templatecontext;
        }

        // Use reflection to access private $course property of renderable
        try {
            $reflection = new \ReflectionClass($activity);
            $property = $reflection->getProperty('course');
            $property->setAccessible(true);
            $course = $property->getValue($activity);
        } catch (\ReflectionException $e) {
            // If reflection fails, return context without modification
            debugging('theme_inteb: Could not access course property: ' . $e->getMessage(), DEBUG_DEVELOPER);
            return $templatecontext;
        }

        // Get teacher context using our extended helper
        $teacherscontext = \theme_inteb\format_remuiformat_helper::get_enrolled_teachers_context(
            $course,
            true // frontlineteacher = true to show ALL without limit
        );

        // Replace teachers section in headerdata
        if (!empty($teacherscontext)) {
            // Convert array to object if necessary (for template consistency)
            $templatecontext->headerdata->teachers = (object)$teacherscontext;
        }

        return $templatecontext;
    }
}
