<?php
// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.

/**
 * Strings for component 'paygw_payu', language 'en' - COMPLETE.
 *
 * @package    paygw_payu
 * @copyright  2024 Orion Cloud Consulting SAS
 * @author     Alonso Arias <soporte@orioncloud.com.co>
 * @license    https://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */

$string['pluginname'] = 'PayU Colombia';
$string['pluginname_desc'] = 'The PayU Colombia payment gateway enables online payments through various methods including credit cards, PSE bank transfers, Nequi, and cash payments.';
$string['gatewayname'] = 'PayU Colombia';
$string['gatewaydescription'] = 'PayU is a leading payment service provider in Latin America, processing secure online payments in Colombia.';

// Configuration strings.
$string['merchantid'] = 'Merchant ID';
$string['merchantid_help'] = 'Your PayU merchant identifier number.';
$string['payuaccountid'] = 'Account ID';
$string['accountid'] = 'Account ID';
$string['accountid_help'] = 'Your PayU account identifier for Colombia.';
$string['apikey'] = 'API Key';
$string['apikey_help'] = 'Your secret API key provided by PayU. Keep this secure!';
$string['apilogin'] = 'API Login';
$string['apilogin_help'] = 'Your API login credential for PayU services.';
$string['testmode'] = 'Test mode';
$string['testmode_help'] = 'Enable test mode to use the PayU sandbox environment for testing payments.';
$string['debugmode'] = 'Debug mode';
$string['debugmode_help'] = 'Enable debug mode to log detailed transaction information for troubleshooting.';

// Payment methods configuration.
$string['paymentmethods'] = 'Payment Methods Configuration';
$string['enabledmethods'] = 'Enabled payment methods';
$string['enabledmethods_help'] = 'Select which payment methods should be available to users. At least one method must be enabled.';

// Payment methods.
$string['paymentmethod'] = 'Payment method';
$string['choosepaymentmethod'] = 'Choose payment method';
$string['creditcard'] = 'Credit/Debit Card';
$string['pse'] = 'PSE - Bank Transfer';
$string['nequi'] = 'Nequi';
$string['bancolombia'] = 'Bancolombia Button';
$string['googlepay'] = 'Google Pay';
$string['cash'] = 'Cash Payment';
$string['efecty'] = 'Efecty';
$string['otherscash'] = 'Other Cash Networks';
$string['bankreferenced'] = 'Bank Referenced';
$string['cashmethod'] = 'Cash payment network';

// Form fields.
$string['cardholder'] = 'Cardholder name';
$string['cardnumber'] = 'Card number';
$string['expmonth'] = 'Expiry month';
$string['expyear'] = 'Expiry year';
$string['cvv'] = 'CVV';
$string['cardnetwork'] = 'Card network';
$string['installments'] = 'Installments';
$string['installment'] = 'installment';
$string['phone'] = 'Phone number';
$string['documentnumber'] = 'Document number';
$string['documenttype'] = 'Document type';
$string['email'] = 'Email address';
$string['address'] = 'Address';
$string['city'] = 'City';
$string['state'] = 'State/Province';
$string['postalcode'] = 'Postal code';

// PSE specific.
$string['psebank'] = 'Bank';
$string['selectbank'] = 'Select your bank';
$string['usertype'] = 'Person type';
$string['personnatural'] = 'Natural Person';
$string['personjuridica'] = 'Legal Entity';
$string['nequi_phone_help'] = 'Enter your 10-digit mobile number starting with 3';

// Google Pay.
$string['googlepaytoken'] = 'Google Pay Token';
$string['googlepaytoken_help'] = 'The payment token generated by Google Pay';

// Cache settings.
$string['cachesettings'] = 'Cache Settings';
$string['enablecache'] = 'Enable caching';
$string['enablecache_help'] = 'Enable caching of PSE bank lists and other data to improve performance.';

// Notification settings.
$string['notificationsettings'] = 'Notification Settings';
$string['enablenotifications'] = 'Enable email notifications';
$string['enablenotifications_help'] = 'Send email notifications to users about their payment status.';

// Callback URL.
$string['callbackurl'] = 'Callback URL';
$string['callbackurl_help'] = 'Configure this URL in your PayU merchant panel for payment notifications.';

// Payment interface.
$string['paymentdetails'] = 'Payment Details';
$string['ordersummary'] = 'Order Summary';
$string['description'] = 'Description';
$string['amount'] = 'Amount';

// Payment processing.
$string['submitpayment'] = 'Process Payment';
$string['processingpayment'] = 'Processing payment...';
$string['paymentsuccess'] = 'Payment successful!';
$string['paymentpending'] = 'Payment pending';
$string['paymenterror'] = 'Payment error';
$string['viewreceipt'] = 'View Receipt';
$string['viewpayment'] = 'View Payment Details';
$string['loadingpaymentgateway'] = 'Loading payment gateway...';

// Payment instructions.
$string['instruction_pse'] = 'You will be redirected to your bank\'s secure website to complete the payment.';
$string['instruction_nequi'] = 'You will receive a push notification on your Nequi app to authorize the payment.';
$string['instruction_cash'] = 'Print or save the payment receipt and pay at any authorized location.';
$string['instruction_bancolombia'] = 'You will be redirected to Bancolombia to complete the payment.';

// Airline specific.
$string['airline'] = 'Airline';
$string['airline_code'] = 'Airline code';
$string['airline_transaction'] = 'Airline transaction';
$string['errorgetairlines'] = 'Error retrieving airlines list: {$a}';

// Test mode.
$string['sandboxmode'] = 'Sandbox Mode Configuration';
$string['sandboxmode_help'] = 'You are configuring the gateway in test mode. Use the credentials below for testing.';
$string['autofillsandbox'] = 'Auto-fill Sandbox Credentials';
$string['testcredentials'] = 'PayU Sandbox Credentials';
$string['autofillprompt'] = 'Do you want to auto-fill the sandbox credentials for testing?';
$string['credentialsfilled'] = 'Sandbox credentials have been filled successfully.';
$string['sandboxactive'] = 'SANDBOX MODE ACTIVE';
$string['testcards'] = 'Test Credit Cards';
$string['selecttestcard'] = 'Select a test card';
$string['choosetestcard'] = 'Choose a test card';
$string['filltestcard'] = 'Fill Test Card';
$string['testcardfilled'] = 'Test card data has been filled.';
$string['testpse'] = 'Test PSE Bank Transfer';
$string['testpse_help'] = 'Use the test bank credentials for PSE testing.';
$string['filltestpse'] = 'Fill Test PSE Data';
$string['testpsefilled'] = 'Test PSE data has been filled.';
$string['testnequi'] = 'Test Nequi Payment';
$string['testnequi_help'] = 'Use test phone number for Nequi testing.';
$string['filltestnequi'] = 'Fill Test Nequi Data';
$string['testnequifilled'] = 'Test Nequi data has been filled.';
$string['testmodeactive'] = 'Test Mode Active';
$string['testmodeactive_help'] = 'You are in PayU sandbox mode. Transactions will not be real.';
$string['testmodeinfo1'] = 'No real money will be charged';
$string['testmodeinfo2'] = 'Use test credit cards provided';
$string['testmodeinfo3'] = 'Transactions can be verified in PayU sandbox dashboard';

// Message notifications.
$string['messagesubject_payment_receipt'] = 'Payment Receipt';
$string['messagesubject_payment_pending'] = 'Payment Pending';
$string['messagesubject_payment_error'] = 'Payment Failed';
$string['messagesubject_cashreminder'] = 'Cash Payment Reminder';

$string['message_payment_success'] = 'Dear {$a->fullname},

Your payment of {$a->amount} has been successfully processed.

Payment ID: {$a->paymentid}
Transaction ID: {$a->transactionid}
Payment Method: {$a->paymentmethod}
Date: {$a->date}

Thank you for your payment.';

$string['message_payment_pending'] = 'Dear {$a->fullname},

Your payment of {$a->amount} is currently pending.

Payment ID: {$a->paymentid}
Status: {$a->state}
Date: {$a->date}

We will notify you once the payment is confirmed.';

$string['message_payment_error'] = 'Dear {$a->fullname},

There was an error processing your payment of {$a->amount}.

Payment ID: {$a->paymentid}
Status: {$a->state}
Date: {$a->date}

Please try again or contact support if the problem persists.';

$string['message_cash_reminder'] = 'Dear {$a->fullname},

This is a reminder about your pending cash payment.

Amount: {$a->amount}
Reference: {$a->reference}
Expiration date: {$a->expirationdate}

Please complete your payment at any authorized location. You can view and print your payment receipt here:
{$a->receipturl}';

// Errors.
$string['gatewaynotconfigured'] = 'Payment gateway is not properly configured.';
$string['currencynotsupported'] = 'Currency {$a} is not supported by PayU Colombia.';
$string['invalidpayment'] = 'Invalid payment record.';
$string['invaliduser'] = 'Invalid user for this payment.';
$string['invalidpaymentmethod'] = 'Invalid payment method selected.';
$string['merchantidinvalid'] = 'Merchant ID must be numeric.';
$string['accountidinvalid'] = 'Account ID must be numeric.';
$string['atleastonemethodrequired'] = 'At least one payment method must be enabled.';
$string['errorgetbanks'] = 'Error retrieving bank list: {$a}';
$string['errorgetmethods'] = 'Error retrieving payment methods: {$a}';
$string['errortransaction'] = 'Transaction error: {$a}';
$string['errorquerytransaction'] = 'Error querying transaction: {$a}';
$string['errorrefund'] = 'Refund error: {$a}';
$string['errorcurlconnection'] = 'Connection error: {$a}';
$string['errorhttpcode'] = 'HTTP error code: {$a}';
$string['errorjsonparse'] = 'Error parsing response from PayU.';
$string['errorconnection'] = 'Unable to connect to PayU servers.';
$string['unknownstate'] = 'Unknown transaction state: {$a}';
$string['invalidphone'] = 'Invalid phone number format. Must be 10 digits starting with 3.';
$string['invalidsignature'] = 'Invalid payment signature.';
$string['invalidmerchant'] = 'Invalid merchant configuration.';
$string['invalidreference'] = 'Invalid payment reference.';

// Privacy.
$string['privacy:metadata:paygw_payu:payu'] = 'Information sent to PayU for payment processing.';
$string['privacy:metadata:paygw_payu:payu:fullname'] = 'The full name of the user making the payment.';
$string['privacy:metadata:paygw_payu:payu:email'] = 'The email address of the user.';
$string['privacy:metadata:paygw_payu:payu:phone'] = 'The phone number provided for the payment.';
$string['privacy:metadata:paygw_payu:payu:documentnumber'] = 'The identification document number.';
$string['privacy:metadata:paygw_payu:payu:address'] = 'The billing or shipping address.';
$string['privacy:metadata:paygw_payu:payu:creditcard'] = 'Credit card information (transmitted securely to PayU).';
$string['privacy:metadata:paygw_payu:payu:amount'] = 'The payment amount.';
$string['privacy:metadata:paygw_payu:payu:currency'] = 'The payment currency.';

$string['privacy:metadata:paygw_payu:database'] = 'Transaction records stored locally.';
$string['privacy:metadata:paygw_payu:database:paymentid'] = 'The internal payment ID.';
$string['privacy:metadata:paygw_payu:database:payu_order_id'] = 'The PayU order identifier.';
$string['privacy:metadata:paygw_payu:database:payu_transaction_id'] = 'The PayU transaction identifier.';
$string['privacy:metadata:paygw_payu:database:state'] = 'The transaction state.';
$string['privacy:metadata:paygw_payu:database:payment_method'] = 'The payment method used.';
$string['privacy:metadata:paygw_payu:database:amount'] = 'The transaction amount.';
$string['privacy:metadata:paygw_payu:database:currency'] = 'The transaction currency.';
$string['privacy:metadata:paygw_payu:database:timecreated'] = 'When the transaction was created.';